name: Create Dev Environment
 
on:
  workflow_dispatch:
    inputs:
     env_name:
      description: name for the environment to be created
      required: true
 
     user_id:
      description: AAD object id for the user
      required: true 
jobs:
  Create-Environments:
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1
 
    steps:
    - uses: actions/checkout@v3
      with:
        lfs: true
 
    - name: Install PAC
      uses: microsoft/powerplatform-actions/actions-install@latest

     
    - name: Create Developer Environment
      uses: microsoft/powerplatform-actions/create-environment@latest
      with:
        app-id: ${{secrets.CLIENT_ID}}
        client-secret: ${{ secrets.PowerPlatformSPN }}
        tenant-id: ${{secrets.TENANT_ID}}
        name: ${{ github.event.inputs.env_name }}_Dev
        type: Developer
        domain: ${{ github.event.inputs.env_name }}Dev
    - name: assign-user to developer environment
      uses:  microsoft/powerplatform-actions/assign-user@latest
      with:
        app-id: ${{secrets.CLIENT_ID}}
        client-secret: ${{ secrets.PowerPlatformSPN }}
        tenant-id: ${{secrets.TENANT_ID}}
        environment: 'https://${{ github.event.inputs.env_name }}Dev.dynamics.com'
        user: ${{ github.event.inputs.user_id }}
        role: System Administrator
