name: Create Dev Environment
on:
  workflow_dispatch:
    inputs:
     env_name:
      description: name for the environment to be created
      required: true
 
     user_id:
      description: AAD object id for the user
      required: true 
env:
#edit your values here
  ENVIRONMENT_URL: 'https://orge554fa74.crm.dynamics.com'
  CLIENT_ID: 'a9e67a7e-0f02-4a33-ac96-ee810adca3e1'
  TENANT_ID: '64e9d33b-a08c-4985-8735-a458851b2816'
  USERNAME: 'admin@M365x76321320.onmicrosoft.com'
  PASSWORD: 'cHe#=z70FvR30(V='

permissions:
  contents: write

jobs:
  Create-Environments:
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1
 
    steps:
    - uses: actions/checkout@v3
      with:
        lfs: true
 
    - name: Install PAC
      uses: microsoft/powerplatform-actions/actions-install@latest

     
    - name: Create Developer Environment
      uses: microsoft/powerplatform-actions/create-environment@latest
      with:
       # app-id: ${{env.CLIENT_ID}}
       # client-secret: ${{ secrets.PowerPlatformSPN }}
        user-name: ${{ env.USERNAME }}
        password-secret: ${{ env.PASSWORD }}
        tenant-id: ${{env.TENANT_ID}}
        name: ${{ github.event.inputs.env_name }}_Dev
        type: Developer
    - name: assign-user to developer environment
      uses:  microsoft/powerplatform-actions/assign-user@latest
      with:
        app-id: ${{secrets.CLIENT_ID}}
        client-secret: ${{ secrets.PowerPlatformSPN }}
        tenant-id: ${{secrets.TENANT_ID}}
        environment: 'https://${{ github.event.inputs.env_name }}Dev.dynamics.com'
        user: ${{ github.event.inputs.user_id }}
        role: System Administrator
